apiVersion: v1
kind: Service
metadata:
  name: {{ include "foodapp.fullname" . }}
  labels:
    {{- include "foodapp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
    - name: management
      port: {{ .Values.service.managementPort }}
      targetPort: management
  selector:
    {{- include "foodapp.selectorLabels" . | nindent 4 }}
