apiVersion: v1
kind: ConfigMap
metadata:
  name: foodapp-config-local
  namespace: foodapp
data:
  SPRING_PROFILES_ACTIVE: "dev"
  SPRING_DATASOURCE_URL: "jdbc:mysql://foodapp-mysql.foodapp.svc.cluster.local:3306/foodapp?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Kolkata"
  MANAGEMENT_OTLP_METRICS_EXPORT_URL: "http://otel-collector.observability.svc.cluster.local:4318/v1/metrics"
  MANAGEMENT_OPENTELEMETRY_TRACING_EXPORT_OTLP_ENDPOINT: "http://otel-collector.observability.svc.cluster.local:4318/v1/traces"
  MANAGEMENT_OPENTELEMETRY_LOGGING_EXPORT_OTLP_ENDPOINT: "http://otel-collector.observability.svc.cluster.local:4318/v1/logs"